name: check_run-requested_action

on:
  check_run:
    types: [requested_action]

jobs:
  foo:
    name: check_run-requested_action
    runs-on: ubuntu-latest
    steps:
      - name: Event context info
        run: |
          cat <<EOF
          github: ${{toJSON(github)}}
          env: ${{toJSON(env)}}
          vars: ${{toJSON(vars)}}
          job: ${{toJSON(job)}}
          steps: ${{toJSON(steps)}}
          runner: ${{toJSON(runner)}}
          secrets: ${{toJSON(secrets)}}
          strategy: ${{toJSON(strategy)}}
          matrix: ${{toJSON(matrix)}}
          needs: ${{toJSON(needs)}}
          inputs: ${{toJSON(inputs)}}
