name: check_run-requested_action

on:
  check_run:
    types: [requested_action]

jobs:
  foo:
    name: check_run-requested_action
    runs-on: ubuntu-latest
    steps:
      - name: Event context info
        run: |
          cat <<EOF
          github: ${{github}}
          env: ${{env}}
          vars: ${{vars}}
          job: ${{job}}
          jobs: ${{jobs}}
          steps: ${{steps}}
          runner: ${{runner}}
          secrets: ${{secrets}}
          strategy: ${{strategy}}
          matrix: ${{matrix}}
          needs: ${{needs}}
          inputs: ${{inputs}}
