name: issues-unlabeled

on:
  issues:
    types: [unlabeled]

jobs:
  foo:
    name: issues-unlabeled
    runs-on: ubuntu-latest
    steps:
      - name: Event context info
        run: |
          cat <<EOF
          github: ${{github}}
          env: ${{env}}
          vars: ${{vars}}
          job: ${{job}}
          steps: ${{steps}}
          runner: ${{runner}}
          secrets: ${{secrets}}
          strategy: ${{strategy}}
          matrix: ${{matrix}}
          needs: ${{needs}}
          inputs: ${{inputs}}
