name: merge_group-checks_requested

on:
  merge_group:
    types: [checks_requested]

jobs:
  foo:
    name: merge_group-checks_requested
    runs-on: ubuntu-latest
    steps:
      - name: Event context info
        run: |
          cat <<EOF
          github: ${{github}}
          env: ${{env}}
          vars: ${{vars}}
          job: ${{job}}
          steps: ${{steps}}
          runner: ${{runner}}
          secrets: ${{secrets}}
          strategy: ${{strategy}}
          matrix: ${{matrix}}
          needs: ${{needs}}
          inputs: ${{inputs}}
