name: pull_request-converted_to_draft

on:
  pull_request:
    types: [converted_to_draft]

jobs:
  foo:
    name: pull_request-converted_to_draft
    runs-on: ubuntu-latest
    steps:
      - name: Event context info
        run: |
          cat <<EOF
          github: ${{toJSON(github)}}
          env: ${{toJSON(env)}}
          vars: ${{toJSON(vars)}}
          job: ${{toJSON(job)}}
          steps: ${{toJSON(steps)}}
          runner: ${{toJSON(runner)}}
          secrets: ${{toJSON(secrets)}}
          strategy: ${{toJSON(strategy)}}
          matrix: ${{toJSON(matrix)}}
          needs: ${{toJSON(needs)}}
          inputs: ${{toJSON(inputs)}}
