name: workflow_call

on:
  workflow_call:

jobs:
  foo:
    name: workflow_call
    runs-on: ubuntu-latest
    steps:
      - name: Event context info
        run: |
          cat <<EOF
          github: ${{github}}
          env: ${{env}}
          vars: ${{vars}}
          job: ${{job}}
          steps: ${{steps}}
          runner: ${{runner}}
          secrets: ${{secrets}}
          strategy: ${{strategy}}
          matrix: ${{matrix}}
          needs: ${{needs}}
          inputs: ${{inputs}}
